apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedge-operator-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubedge-operator-helm
  template:
    metadata:
      labels:
        name: kubedge-operator-helm
    spec:
      containers:
        - name: kubedge-operator-helm
          image: hack4easy/kubedge-operator-helm-dev:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
